### ISSUE TITLE
Download document as template doesn't purge data or reduce file size

### ISSUE THREAD

**Issue by strmca** [gristlabs/grist-core#718] opened 2023-11-02 08:03 UTC
Note: I initially submitted this as a bug in Grist-Electron. (https://github.com/gristlabs/grist-electron/issues/14) 2 weeks ago with no response.  This issue exists as well in Grist-Core (as installed this evening v1.1.6 in Docker)   

When downloading document and choosing "Remove All Data but keep the structure to use as a template", the download size is the same as "Remove document history". I would expect the document containing structure only to be very small in comparison.

For instance, one of my current databases with some attachments exports as 84MB with full history, 72MB with no document history and 72mb with only the database structure.

This would make it prohibitive to distribute a very mature database file (this one may grow to about .5 - 1GB if I continue adding the usual attachments) to another person in my community both for size and possible recoverable data.

**Comment by fflorent** [comment] 2023-11-02 08:57
Indeed, I could reproduce the issue!

Seems to me actually not very complicated to fix, here is the code where the data are purged:
https://github.com/gristlabs/grist-core/blob/d29e23efe83d71f0e3daf921898cac2efcdce8cc/app/server/lib/DocWorker.ts#L209-L218

If I am not wrong, there are two more tables which should be purged:
 - `_grist_Attachments`
 - `_gristsys_Files`

**Comment by strmca** [comment] 2023-11-03 04:17
> Indeed, I could reproduce the issue!
> 
> Seems to me actually not very complicated to fix, here is the code where the data are purged:
> 
> If I am not wrong, there are two more tables which should be purged:
> 
>     * `_grist_Attachments`
> 
>     * `_gristsys_Files`

Thanks for confirming that! I suspect you're right.  My development life is a long way in the past and I thought I was going a little mad for a bit.  Hope it's as easy a fix as you say! 

FYI: I double checked after I posted this issue, if I re-import the "template" I see no data.

**Comment by fflorent** [comment] 2023-11-03 10:29
I flagged this issue as `good-first-issue` in order to attract new contributors. In such a perspective, it would require to wait a little bit.

However I wonder how much it is a pain for you? If that's annoying, I will assign it to myself.

Here is a workaround until it is fixed. Tested on Linux (and probably working on Mac) and assuming you're comfortable with command lines (shells):
0. Install sqlite3 if that's not already installed (`which sqlite3` should return something)
1. Download your Grist document without data (aka "Remove All Data but keep the structure to use as a template").
2. Once downloaded, run this commands (be sure to replace `/PATH/TO/MY_FILE.grist` with the right path): `sqlite3 /PATH/TO/MY_FILE.grist  "delete from _grist_Attachments; delete from _gristsys_Files; vacuum;"`
3. Then you should observe that the size has reduced considerably, and you should be able to reupload it on Grist.

> FYI: I double checked after I posted this issue, if I re-import the "template" I see no data.

That's because the attachments are still stored despite being not referenced in any cell.

**Comment by strmca** [comment] 2023-11-04 00:58
No, I'm in no hurry at all, especially with the workaround.  Though it may save you guys some bandwidth if people often download empty templates instead of the full example files?  

I tested out the workaround on my Ubuntu 20.04LTS server.  The file went from 101MB to 352KB and imported exactly as I would have expected.  Thank you so much!

**Closed** 2023-11-08 20:15 UTC
Labels: good first issue

**Comment by strmca** [comment] 2023-11-10 04:23
Thank you!
