### ISSUE TITLE
Feature request: disable guest usage

### ISSUE THREAD

**Issue by helmut72** [gristlabs/grist-core#144] opened 2022-02-20 20:23 UTC
Would be great to have an option to enable/disable guest usage. Don't want to waste resources if someone find the url and play with it. Thank you.

**Comment by interru** [comment] 2022-02-21 01:48
Duplicate of #140

**Comment by paulfitz** [comment] 2022-02-21 03:10
Thanks @helmut72, @interru, it makes sense. Will track this at #140.

**Closed by paulfitz** 2022-02-21 03:10 UTC
